# Generated by Django 5.1.2 on 2024-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_username_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Rol'),
        ),
    ]
