# Generated by Django 5.1.2 on 2024-10-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiopropio',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultados',
            name='archivo_resultado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DatosEstandarizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezados', models.JSONField()),
                ('contenido', models.JSONField()),
                ('fecha_procesamiento', models.DateField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.archivocargado')),
            ],
        ),
    ]
