# Generated by Django 5.1.2 on 2024-10-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estudiopropio_resumen_resultados_archivo_resultado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiopropio',
            name='resumen',
        ),
        migrations.AlterField(
            model_name='estudiopropio',
            name='tipo_archivo',
            field=models.CharField(max_length=100),
        ),
    ]
