# Generated by Django 5.1.2 on 2024-10-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_estudiopropio_resumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiopropio',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivocargado',
            name='formato',
            field=models.CharField(max_length=50),
        ),
    ]
