# Generated by Django 5.1.2 on 2024-10-21 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_estudiopropio_resumen_alter_archivocargado_formato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiopropio',
            name='usuario',
        ),
        migrations.CreateModel(
            name='EstudioArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('formato', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('ruta', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='datosestandarizados',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudioarchivo'),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudioarchivo'),
        ),
        migrations.DeleteModel(
            name='ArchivoCargado',
        ),
        migrations.DeleteModel(
            name='EstudioPropio',
        ),
    ]
