# Generated by Django 5.1.2 on 2024-10-21 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_estudiopropio_usuario_estudioarchivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analisis', models.CharField(max_length=100)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.JSONField(blank=True, null=True)),
                ('fecha_analisis', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='estudio',
        ),
        migrations.AlterField(
            model_name='datosestandarizados',
            name='archivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.archivoresultados'),
        ),
        migrations.AlterField(
            model_name='visualizaciondatos',
            name='resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.archivoresultados'),
        ),
        migrations.CreateModel(
            name='EstudioPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archivoresultados',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiopdf'),
        ),
        migrations.DeleteModel(
            name='EstudioArchivo',
        ),
        migrations.DeleteModel(
            name='Resultados',
        ),
    ]
