# Generated by Django 5.1.2 on 2024-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_archivoresultados_remove_resultados_estudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosestandarizados',
            name='prueba',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
