# Generated by Django 5.1.2 on 2024-10-24 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_datosestandarizados_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_cambio_contraseña',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
