# Generated by Django 5.1.2 on 2024-10-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usuario_fecha_cambio_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_cambio_contraseña',
            new_name='password_change_date',
        ),
    ]
