# Generated by Django 5.1.2 on 2024-10-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_fecha_cambio_contraseña_usuario_password_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
