# Generated by Django 5.1.2 on 2024-10-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_usuario_mfa_enabled_usuario_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
