# Generated by Django 5.1.2 on 2024-10-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_usuario_mfa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mfa_enabled',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mfa_secret',
        ),
        migrations.AddField(
            model_name='usuario',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
