# Generated by Django 5.1.2 on 2024-10-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_usuario_mfa_enabled_remove_usuario_mfa_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='temp_password_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
