# Generated by Django 5.1.2 on 2024-10-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_usuario_last_password_change_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='temp_password',
            new_name='verify_code',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='temp_password_created',
            new_name='verify_code_created',
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
