# Generated by Django 5.1.2 on 2024-10-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auditoriausuario_delete_userauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_for_login',
            field=models.BooleanField(default=False),
        ),
    ]
