# Generated by Django 5.1.2 on 2024-11-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_usuario_favorite_color_alter_usuario_pets_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('cod_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_ubicaciones', to='core.ubicacion')),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.ubicacion'),
        ),
    ]
