# Generated by Django 5.1.2 on 2024-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ubicacion_usuario_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ubicacion_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
